apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: ksa-dengan-workload-identity # HARUS sesuai service account yang diberi IAM
      containers:
        - name: todo-app
          image: asia-southeast1-docker.pkg.dev/hafiz-458806/registry-image/todo-app:v1
          ports:
            - containerPort: 3000